import type { Invite, InvitePage } from "./types";

/**
 * Conteúdo de exemplo usado quando o Supabase ainda não está configurado.
 * Serve como template inicial do produto: é exatamente a estrutura que o
 * painel cria para um evento novo.
 */

const pages: InvitePage[] = [
  {
    id: "demo-cover",
    position: 0,
    kind: "cover",
    is_visible: true,
    eyebrow: "Com a bênção de quem caminhou conosco",
    title: null,
    subtitle: null,
    body: null,
    background_url: null,
    background_kind: "color",
    overlay: 0,
    config: {},
  },
  {
    id: "demo-menu",
    position: 1,
    kind: "menu",
    is_visible: true,
    eyebrow: "Toque nos ícones",
    title: "para interagir",
    subtitle: null,
    body: null,
    background_url: null,
    background_kind: "color",
    overlay: 0.45,
    config: {
      items: [
        { icon: "location", label: "Saiba como chegar", target: "location" },
        { icon: "gift", label: "Para nos presentear", target: "gift" },
        { icon: "rsvp", label: "Confirmar presença", target: "rsvp" },
        { icon: "gallery", label: "Nossos momentos", target: "gallery" },
        { icon: "dresscode", label: "Dress code", target: "dresscode" },
        { icon: "guide", label: "Manual dos convidados", target: "guide" },
      ],
    },
  },
  {
    id: "demo-rsvp",
    position: 2,
    kind: "rsvp",
    is_visible: true,
    eyebrow: "Confirmação de presença",
    title: "Quem vem com você?",
    subtitle: null,
    body: "Confirme cada pessoa da família até o dia 30 de novembro. Se algo mudar, é só voltar neste link e atualizar.",
    background_url: null,
    background_kind: "color",
    overlay: 0,
    config: {},
  },
  {
    id: "demo-location",
    position: 3,
    kind: "location",
    is_visible: true,
    eyebrow: "Saiba como chegar",
    title: "O lugar",
    subtitle: null,
    body: "Estacionamento no local. Recomendamos chegar 30 minutos antes.",
    background_url: null,
    background_kind: "color",
    overlay: 0,
    config: {},
  },
  {
    id: "demo-gift",
    position: 4,
    kind: "gift",
    is_visible: true,
    eyebrow: "Para nos presentear",
    title: "Presente via PIX",
    subtitle: null,
    body: "Sua presença já é o maior presente. Mas se quiser nos mimar, ficamos felizes com qualquer valor.",
    background_url: null,
    background_kind: "color",
    overlay: 0,
    config: {},
  },
  {
    id: "demo-gallery",
    position: 5,
    kind: "gallery",
    is_visible: true,
    eyebrow: "Nossos momentos",
    title: "Três anos em fotos",
    subtitle: null,
    body: null,
    background_url: null,
    background_kind: "color",
    overlay: 0,
    config: { gallery: [] },
  },
  {
    id: "demo-dresscode",
    position: 6,
    kind: "content",
    is_visible: true,
    eyebrow: "Dress code",
    title: "Esporte fino",
    subtitle: null,
    body: "Elas: vestido midi ou longo.\nEles: calça social e camisa.\n\nDeixamos o branco reservado para os anfitriões.",
    background_url: null,
    background_kind: "color",
    overlay: 0.4,
    config: { slug: "dresscode" },
  },
  {
    id: "demo-guide",
    position: 7,
    kind: "content",
    is_visible: true,
    eyebrow: "Manual dos convidados",
    title: "Boas-vindas",
    subtitle: null,
    body: "18h — Recepção\n19h — Jantar\n21h — Festa\n\nCrianças são muito bem-vindas.\nO espaço é ao ar livre: leve um casaquinho.",
    background_url: null,
    background_kind: "color",
    overlay: 0.4,
    config: { slug: "guide" },
  },
  {
    id: "demo-closing",
    position: 8,
    kind: "closing",
    is_visible: true,
    eyebrow: null,
    title: "Esperamos por você",
    subtitle: null,
    body: null,
    background_url: null,
    background_kind: "color",
    overlay: 0.3,
    config: {},
  },
];

export const demoInvite: Invite = {
  event: {
    id: "demo-event",
    slug: "demo",
    couple_names: "Guilherme & Marina",
    monogram: "GM",
    title: "Bodas de Trigo",
    blessing_line: "Três anos depois do sim, a festa que faltava",
    event_date: "2026-12-12T19:00:00-03:00",
    venue_name: "Casa das Oliveiras",
    venue_address: "Rua das Palmeiras, 120 — Itaipava, Petrópolis/RJ",
    venue_maps_url: null,
    venue_lat: null,
    venue_lng: null,
    music_url: null,
    theme: {},
    pix_key: "convite@exemplo.com.br",
    pix_key_owner: "Guilherme Assis",
    pix_city: "Sao Paulo",
    pix_suggestions: [50, 100, 200],
    whatsapp_template: null,
    base_url: null,
  },
  pages,
  household: {
    id: "demo-household",
    event_id: "demo-event",
    slug: "demo",
    family_name: "Família Oliveira",
    greeting: "Ricardo e família",
    phone: null,
    note: null,
    invite_status: "pending",
    invite_sent_at: null,
    responded_at: null,
    guests: [
      { id: "g1", name: "Ricardo Oliveira", is_child: false, position: 0, status: "pending" },
      { id: "g2", name: "Carla Oliveira", is_child: false, position: 1, status: "pending" },
      { id: "g3", name: "Pedro Oliveira", is_child: true, position: 2, status: "pending" },
    ],
  },
};
